name: Create files for an AoC day

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  create-day:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up variables for the day
        id: set_day
        run: |
          DAY=$(date +"%-d")
          echo "DAY=$DAY" >> $GITHUB_OUTPUT
          echo "DAY_DIR=day$DAY" >> $GITHUB_OUTPUT
      - name: Create day folder and files
        run: |
          DAY="${{  steps.set_day.outputs.DAY  }}"
          DAY_DIR="${{  steps.set_day.outputs.DAY_DIR  }}"

          mkdir -p "$DAY_DIR"

          echo "inp = open(\"${DAY_DIR}/input.txt\").read().splitlines()" > "${DAY_DIR}/part1.py"
          echo "inp = open(\"${DAY_DIR}/input.txt\").read().splitlines()" > "${DAY_DIR}/part2.py"
          echo "" > "${DAY_DIR}/input.txt"

      - name: Commit and push
        run: |
          DAY="${{  steps.set_day.outputs.DAY  }}"
          
          if git diff --quiet; then
            echo "No changes to commit :("
            exit 1
          fi
          
          git add .
          git commit -m "Create AoC day ${DAY} files"
          git push